### ISSUE TITLE
Skonfigurowanie automatycznego budowania

### ISSUE THREAD

**Issue by natalia-szymczyk** [natalia-szymczyk/text-transformer-io#10]

**Comment by natalia-szymczyk** [comment]
GitHub Actions

**Comment by mat-sw** [comment]
W pliku ci.yml jest już gotowe budowanie, żeby pobrać paczkę Jar należy wejść w Actions -> Kliknąć Workflow -> na dole w zakładce Artifacts jest do pobrania paczka
